import json
import random

with open("data/corpus.jsonl") as f:
    messages = [json.loads(line) for line in f]

with open("data/queries.json") as f:
    queries = json.load(f)

# Find messages that are generated by templates
# e.g., "mera notes library me reh gaya"
template_msgs = [m for m in messages if len(m["text"].split()) >= 4 and m["text"] != "<media>"]

random.seed(42)
selected = random.sample(template_msgs, 32)

for i, q in enumerate(queries):
    if not q["hard"]:
        msg = selected.pop()
        q["query"] = msg["text"]  # Exact match query
        q["gold_id"] = msg["id"]
        q["gold_sender"] = msg["sender"]
        q["gold_ts"] = msg["ts"]
        q["gold_text"] = msg["text"]
        q["zero_overlap"] = False

with open("data/queries.json", "w") as f:
    json.dump(queries, f, indent=2)
