import random

base_sentences = [
    ("bhai {name} ko bolna ki aaj tak aa jaye.", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("bhai {name} ko bolna ki kal tak aa jaye.", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("kal 2 baje koi class h kya?", []),
    ("kal 4 baje koi class h kya?", []),
    ("aaj shaam ko koi class h kya?", []),
    ("maine 8 baje ka alarm lagaya tha, miss ho gaya.", []),
    ("maine 9 baje ka alarm lagaya tha, miss ho gaya.", []),
    ("kisi ke paas dbms ke notes hain kya?", []),
    ("kisi ke paas os ke notes hain kya?", []),
    ("kisi ke paas dsa ke notes hain kya?", []),
    ("kisi ke paas cn ke notes hain kya?", []),
    ("mujhe 4 baje canteen me milna.", []),
    ("mujhe shaam ko library me milna.", []),
    ("mera bag auditorium me reh gaya tha.", []),
    ("mera bag gym me reh gaya tha.", []),
    ("mera charger lab me chhut gaya.", []),
    ("aaj hostel ki light nahi aa rahi.", []),
    ("aaj lab me light nahi hai.", []),
    ("{name} ne bola tha ki wo kal aayega.", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("{name} ne bola tha ki wo aaj aayega.", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("bhai 10 pages ka printout nikalna hai.", []),
    ("bhai 20 pages ka printout nikalna hai.", []),
    ("bhai 50 pages ka printout nikalna hai.", []),
    ("mujhe lag raha hai maths me back aayegi.", []),
    ("mujhe lag raha hai physics me back aayegi.", []),
    ("kya {name} aaj class aaya tha?", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("kya {name} kal class aaya tha?", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("wifi department me bilkul nahi chal raha.", []),
    ("wifi hostel me bilkul nahi chal raha.", []),
    ("bhookh lagi hai, canteen chalein?", []),
    ("bhookh lagi hai, mess chalein?", []),
    ("assignment aaj tak submit karna hai.", []),
    ("assignment kal tak submit karna hai.", []),
    ("assignment 5 baje tak submit karna hai.", []),
    ("yeh os ka syllabus kab khatam hoga.", []),
    ("yeh dbms ka syllabus kab khatam hoga.", []),
    ("sir ne aaj attendance li thi kya?", []),
    ("sir ne kal attendance li thi kya?", []),
    ("bhai mere paas sirf 50 rupe bache hain.", []),
    ("bhai mere paas sirf 100 rupe bache hain.", []),
    ("kal se os padhna shuru karunga.", []),
    ("aaj se dbms padhna shuru karunga.", []),
    ("kisi ne mera charger dekha kya lab me?", []),
    ("kisi ne mera charger dekha kya library me?", []),
    ("abhi 12 baj gaye aur neend aa rahi hai.", []),
    ("abhi 2 baj gaye aur neend aa rahi hai.", []),
    ("kal {name} ka birthday hai na?", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("mujhe kal subah ghar nikalna hai.", []),
    ("mujhe kal shaam ko ghar nikalna hai.", []),
    ("aaj dopahar me baarish ho rahi thi.", []),
    ("aaj subah baarish ho rahi thi.", []),
    ("kya kisi ne dsa ki assignment complete ki?", []),
    ("kya kisi ne cn ki assignment complete ki?", []),
    ("mujhe 2 din ki chhutti chahiye.", []),
    ("mujhe 4 din ki chhutti chahiye.", []),
    ("{name} kahan hai yaar, call nahi utha raha.", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("aaj parking me bahut bheed thi.", []),
    ("aaj canteen me bahut bheed thi.", []),
    ("bhai physics ka practical file ban gaya?", []),
    ("bhai chemistry ka practical file ban gaya?", []),
    ("mujhe 8 baje utha dena please.", []),
    ("mujhe 9 baje utha dena please.", []),
    ("is baar maths ka paper bahut tough tha.", []),
    ("is baar os ka paper bahut tough tha.", []),
    ("kal se roz subah 6 baje uthunga.", []),
    ("kal se roz subah 7 baje uthunga.", []),
    ("bhai 5 minute me pahuch raha hu.", []),
    ("bhai 10 minute me pahuch raha hu.", []),
    ("{name} ne mujhe message kiya tha subah.", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("{name} ne mujhe message kiya tha raat ko.", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("kya aaj os ki class cancel ho gayi?", []),
    ("kya kal maths ki class cancel ho gayi?", []),
    ("mujhe lagta hai {name} ko pata hoga.", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("aaj subah thodi thand lag rahi hai.", []),
    ("aaj raat ko thodi thand lag rahi hai.", []),
    ("kisi ko pata hai library kab khulega?", []),
    ("kisi ko pata hai gym kab khulega?", []),
    ("mujhe is semester 4 subjects clear karne hain.", []),
    ("mujhe is semester 5 subjects clear karne hain.", []),
    ("{name} se notes le lena aaj.", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("{name} se notes le lena kal.", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("mujhe lagta hai kal 2 baje test hai.", []),
    ("mujhe lagta hai aaj 4 baje test hai.", []),
    ("yeh chemistry samajh nahi aa raha.", []),
    ("yeh physics samajh nahi aa raha.", []),
    ("bhai canteen aaja, wait kar raha hu.", []),
    ("bhai parking me aaja, wait kar raha hu.", []),
    ("kya aaj shaam ko kuch plan hai?", []),
    ("kya kal raat ko kuch plan hai?", []),
    ("mujhe apne marks dekhe 3 din ho gaye.", []),
    ("mujhe apne marks dekhe 5 din ho gaye.", []),
    ("{name} ko bol dena ki main late hounga.", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("aaj 5 baje thoda jaldi free ho jaunga.", []),
    ("aaj 6 baje thoda jaldi free ho jaunga.", []),
    ("kisi ne {name} ko dekha kya aaj?", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("mujhe auditorium jana hai 2 baje.", []),
    ("mujhe lab jana hai 4 baje.", []),
    ("bhai 4 log aa rahe hain.", []),
    ("bhai 6 log aa rahe hain.", []),
    ("yeh dbms ka assignment kal 5 baje dena hai.", []),
    ("yeh os ka assignment aaj raat ko dena hai.", []),
    ("kisi ne mera phone dekha kya canteen me?", []),
    ("kisi ne mera phone dekha kya lab me?", []),
    ("kal se roz subah 8 baje uthunga.", []),
    ("kal se roz subah 9 baje uthunga.", []),
    ("is baar cn ka paper bahut tough tha.", []),
    ("is baar dsa ka paper bahut tough tha.", []),
    ("aaj dopahar me thodi dhoop hai.", []),
    ("aaj subah thodi dhoop hai.", []),
    ("sir ne kal shaam ko attendance li thi kya?", []),
    ("sir ne aaj dopahar me attendance li thi kya?", []),
    ("bhai mere paas sirf 10 rupe bache hain.", []),
    ("bhai mere paas sirf 20 rupe bache hain.", []),
    ("mujhe lag raha hai cn me back aayegi.", []),
    ("mujhe lag raha hai dsa me back aayegi.", []),
    ("kisi ke paas physics ke notes hain kya?", []),
    ("kisi ke paas chemistry ke notes hain kya?", []),
    ("kya kal os ki class cancel ho gayi?", []),
    ("kya aaj dbms ki class cancel ho gayi?", []),
    ("abhi 1 baj gaye aur neend aa rahi hai.", []),
    ("abhi 3 baj gaye aur neend aa rahi hai.", []),
    ("mujhe apne marks dekhe 2 din ho gaye.", []),
    ("mujhe apne marks dekhe 4 din ho gaye.", []),
    ("aaj parking me koi hai kya?", []),
    ("aaj canteen me koi hai kya?", []),
    ("kisi ko pata hai department kab khulega?", []),
    ("kisi ko pata hai lab kab khulega?", []),
    ("bhai hostel aaja, wait kar raha hu.", []),
    ("bhai library aaja, wait kar raha hu.", []),
    ("kya kisi ne os ki assignment complete ki?", []),
    ("kya kisi ne maths ki assignment complete ki?", []),
    ("mujhe 1 din ki chhutti chahiye.", []),
    ("mujhe 3 din ki chhutti chahiye.", []),
    ("{name} ko bol dena ki main nahi aa raha.", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("{name} kahan hai yaar, message ka reply nahi kar raha.", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("kya {name} aaj department me tha?", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("kya {name} kal library me tha?", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("mujhe lagta hai {name} so raha hoga.", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("kal {name} ka presentation hai na?", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("aaj {name} ne class attend ki kya?", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("{name} ko bolna mujhe call kare.", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("{name} ka assignment dekha tune?", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("mujhe lagta hai {name} ko sab pata hoga.", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("kal {name} ne mujhe bataya tha iske baare me.", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("{name} ne bola ki exam postpone ho gaya.", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("{name} ki tabiyat kharab hai kya aaj?", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("kya {name} canteen gaya hai?", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("{name} ne mujhe aaj subah milne ko bola tha.", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("mujhe {name} se baat karni thi yaar.", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("aaj {name} ka phone band aa raha hai.", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("{name} ne kal apna laptop yahan chhod diya tha.", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("mujhe lagta hai {name} ko yaad nahi hoga.", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("kya {name} ne attendance mark ki thi?", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("{name} se puchh le, usko notes mil gaye the.", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("kal se barish ho rahi hai yahan.", []),
    ("mess ka khana bilkul acha nahi tha aaj.", []),
    ("kisi ke paas extra pen hai kya?", []),
    ("kya kal chhutti hai college me?", []),
    ("mujhe lagta hai kal practical exam hai.", []),
    ("kisi ne mera id card dekha kya?", []),
    ("aaj ki class bahut lambi thi yaar.", []),
    ("bhai koi placement cell ka update hai kya?", []),
    ("kya {name} kal ghar ja raha hai?", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("mujhe lagta hai {name} party dega aaj.", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("{name} ko bolna book wapas karde meri.", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("kya {name} ne wifi password change kiya?", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("aaj {name} ka mood kharab lag raha tha.", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("{name} ne bola ki trip cancel ho gaya.", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("kya {name} ne project submit kar diya?", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("mujhe lagta hai {name} ko internship mil gayi.", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("kal {name} mere room pe aaya tha.", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("{name} se kehna mujhe shaam ko mil le.", ["Rohit", "Sneha", "Ankit", "Devansh", "Aman", "Priya", "Kritika", "Ishaan"]),
    ("aaj sports complex kiska plan hai?", []),
    ("kisi ko pata hai fest kab se hai?", [])
]

final_sentences = []
for template, names in base_sentences:
    if not names:
        final_sentences.append(template)
    else:
        for name in names:
            final_sentences.append(template.replace("{name}", name))

with open("bank.py", "w") as f:
    f.write(f"BANK = [\n")
    for s in final_sentences:
        f.write(f'    "{s}",\n')
    f.write("]\n")

print(f"Generated {len(final_sentences)} sentences.")
print("-" * 50)
for s in random.Random(9).sample(final_sentences, 30):
    print(s)
