"""Hand-authored Hinglish filler lines used when assembling the synthetic corpus."""

BANK = [
    "bhai Rohit ko bolna ki aaj tak aa jaye.",
    "bhai Sneha ko bolna ki aaj tak aa jaye.",
    "bhai Ankit ko bolna ki aaj tak aa jaye.",
    "bhai Devansh ko bolna ki aaj tak aa jaye.",
    "bhai Aman ko bolna ki aaj tak aa jaye.",
    "bhai Priya ko bolna ki aaj tak aa jaye.",
    "bhai Kritika ko bolna ki aaj tak aa jaye.",
    "bhai Ishaan ko bolna ki aaj tak aa jaye.",
    "bhai Rohit ko bolna ki kal tak aa jaye.",
    "bhai Sneha ko bolna ki kal tak aa jaye.",
    "bhai Ankit ko bolna ki kal tak aa jaye.",
    "bhai Devansh ko bolna ki kal tak aa jaye.",
    "bhai Aman ko bolna ki kal tak aa jaye.",
    "bhai Priya ko bolna ki kal tak aa jaye.",
    "bhai Kritika ko bolna ki kal tak aa jaye.",
    "bhai Ishaan ko bolna ki kal tak aa jaye.",
    "kal 2 baje koi class h kya?",
    "kal 4 baje koi class h kya?",
    "aaj shaam ko koi class h kya?",
    "maine 8 baje ka alarm lagaya tha, miss ho gaya.",
    "maine 9 baje ka alarm lagaya tha, miss ho gaya.",
    "kisi ke paas dbms ke notes hain kya?",
    "kisi ke paas os ke notes hain kya?",
    "kisi ke paas dsa ke notes hain kya?",
    "kisi ke paas cn ke notes hain kya?",
    "mujhe 4 baje canteen me milna.",
    "mujhe shaam ko library me milna.",
    "kal auditorium me bahut crowd tha.",
    "aaj gym me ac nahi chal raha.",
    "lab ka projector phir se kharab ho gaya.",
    "aaj hostel ki light nahi aa rahi.",
    "aaj lab me light nahi hai.",
    "Rohit ne bola tha ki wo kal aayega.",
    "Sneha ne bola tha ki wo kal aayega.",
    "Ankit ne bola tha ki wo kal aayega.",
    "Devansh ne bola tha ki wo kal aayega.",
    "Aman ne bola tha ki wo kal aayega.",
    "Priya ne bola tha ki wo kal aayega.",
    "Kritika ne bola tha ki wo kal aayega.",
    "Ishaan ne bola tha ki wo kal aayega.",
    "Rohit ne bola tha ki wo aaj aayega.",
    "Sneha ne bola tha ki wo aaj aayega.",
    "Ankit ne bola tha ki wo aaj aayega.",
    "Devansh ne bola tha ki wo aaj aayega.",
    "Aman ne bola tha ki wo aaj aayega.",
    "Priya ne bola tha ki wo aaj aayega.",
    "Kritika ne bola tha ki wo aaj aayega.",
    "Ishaan ne bola tha ki wo aaj aayega.",
    "bhai 10 pages ka printout nikalna hai.",
    "bhai 20 pages ka printout nikalna hai.",
    "bhai 50 pages ka printout nikalna hai.",
    "mujhe lag raha hai maths me back aayegi.",
    "mujhe lag raha hai physics me back aayegi.",
    "kya Rohit aaj class aaya tha?",
    "kya Sneha aaj class aaya tha?",
    "kya Ankit aaj class aaya tha?",
    "kya Devansh aaj class aaya tha?",
    "kya Aman aaj class aaya tha?",
    "kya Priya aaj class aaya tha?",
    "kya Kritika aaj class aaya tha?",
    "kya Ishaan aaj class aaya tha?",
    "kya Rohit kal class aaya tha?",
    "kya Sneha kal class aaya tha?",
    "kya Ankit kal class aaya tha?",
    "kya Devansh kal class aaya tha?",
    "kya Aman kal class aaya tha?",
    "kya Priya kal class aaya tha?",
    "kya Kritika kal class aaya tha?",
    "kya Ishaan kal class aaya tha?",
    "wifi department me bilkul nahi chal raha.",
    "wifi hostel me bilkul nahi chal raha.",
    "bhookh lagi hai, canteen chalein?",
    "bhookh lagi hai, mess chalein?",
    "assignment aaj tak submit karna hai.",
    "assignment kal tak submit karna hai.",
    "assignment 5 baje tak submit karna hai.",
    "yeh os ka syllabus kab khatam hoga.",
    "yeh dbms ka syllabus kab khatam hoga.",
    "sir ne aaj attendance li thi kya?",
    "sir ne kal attendance li thi kya?",
    "bhai mere paas sirf 50 rupe bache hain.",
    "bhai mere paas sirf 100 rupe bache hain.",
    "kal se os padhna shuru karunga.",
    "aaj se dbms padhna shuru karunga.",
    "kisi ne mera charger dekha kya lab me?",
    "kisi ne mera charger dekha kya library me?",
    "abhi 12 baj gaye aur neend aa rahi hai.",
    "abhi 2 baj gaye aur neend aa rahi hai.",
    "kal Rohit ka birthday hai na?",
    "kal Sneha ka birthday hai na?",
    "kal Ankit ka birthday hai na?",
    "kal Devansh ka birthday hai na?",
    "kal Aman ka birthday hai na?",
    "kal Priya ka birthday hai na?",
    "kal Kritika ka birthday hai na?",
    "kal Ishaan ka birthday hai na?",
    "mujhe kal subah ghar nikalna hai.",
    "mujhe kal shaam ko ghar nikalna hai.",
    "aaj dopahar me baarish ho rahi thi.",
    "aaj subah baarish ho rahi thi.",
    "kya kisi ne dsa ki assignment complete ki?",
    "kya kisi ne cn ki assignment complete ki?",
    "mujhe 2 din ki chhutti chahiye.",
    "mujhe 4 din ki chhutti chahiye.",
    "Rohit kahan hai yaar, call nahi utha raha.",
    "Sneha kahan hai yaar, call nahi utha raha.",
    "Ankit kahan hai yaar, call nahi utha raha.",
    "Devansh kahan hai yaar, call nahi utha raha.",
    "Aman kahan hai yaar, call nahi utha raha.",
    "Priya kahan hai yaar, call nahi utha raha.",
    "Kritika kahan hai yaar, call nahi utha raha.",
    "Ishaan kahan hai yaar, call nahi utha raha.",
    "aaj parking me bahut bheed thi.",
    "aaj canteen me bahut bheed thi.",
    "bhai physics ka practical file ban gaya?",
    "bhai chemistry ka practical file ban gaya?",
    "mujhe 8 baje utha dena please.",
    "mujhe 9 baje utha dena please.",
    "is baar maths ka paper bahut tough tha.",
    "is baar os ka paper bahut tough tha.",
    "kal se roz subah 6 baje uthunga.",
    "kal se roz subah 7 baje uthunga.",
    "bhai 5 minute me pahuch raha hu.",
    "bhai 10 minute me pahuch raha hu.",
    "Rohit ne mujhe message kiya tha subah.",
    "Sneha ne mujhe message kiya tha subah.",
    "Ankit ne mujhe message kiya tha subah.",
    "Devansh ne mujhe message kiya tha subah.",
    "Aman ne mujhe message kiya tha subah.",
    "Priya ne mujhe message kiya tha subah.",
    "Kritika ne mujhe message kiya tha subah.",
    "Ishaan ne mujhe message kiya tha subah.",
    "Rohit ne mujhe message kiya tha raat ko.",
    "Sneha ne mujhe message kiya tha raat ko.",
    "Ankit ne mujhe message kiya tha raat ko.",
    "Devansh ne mujhe message kiya tha raat ko.",
    "Aman ne mujhe message kiya tha raat ko.",
    "Priya ne mujhe message kiya tha raat ko.",
    "Kritika ne mujhe message kiya tha raat ko.",
    "Ishaan ne mujhe message kiya tha raat ko.",
    "kya aaj os ki class cancel ho gayi?",
    "kya kal maths ki class cancel ho gayi?",
    "mujhe lagta hai Rohit ko pata hoga.",
    "mujhe lagta hai Sneha ko pata hoga.",
    "mujhe lagta hai Ankit ko pata hoga.",
    "mujhe lagta hai Devansh ko pata hoga.",
    "mujhe lagta hai Aman ko pata hoga.",
    "mujhe lagta hai Priya ko pata hoga.",
    "mujhe lagta hai Kritika ko pata hoga.",
    "mujhe lagta hai Ishaan ko pata hoga.",
    "aaj subah thodi thand lag rahi hai.",
    "aaj raat ko thodi thand lag rahi hai.",
    "kisi ko pata hai library kab khulega?",
    "kisi ko pata hai gym kab khulega?",
    "mujhe is semester 4 subjects clear karne hain.",
    "mujhe is semester 5 subjects clear karne hain.",
    "Rohit se notes le lena aaj.",
    "Sneha se notes le lena aaj.",
    "Ankit se notes le lena aaj.",
    "Devansh se notes le lena aaj.",
    "Aman se notes le lena aaj.",
    "Priya se notes le lena aaj.",
    "Kritika se notes le lena aaj.",
    "Ishaan se notes le lena aaj.",
    "Rohit se notes le lena kal.",
    "Sneha se notes le lena kal.",
    "Ankit se notes le lena kal.",
    "Devansh se notes le lena kal.",
    "Aman se notes le lena kal.",
    "Priya se notes le lena kal.",
    "Kritika se notes le lena kal.",
    "Ishaan se notes le lena kal.",
    "mujhe lagta hai kal 2 baje test hai.",
    "mujhe lagta hai aaj 4 baje test hai.",
    "yeh chemistry samajh nahi aa raha.",
    "yeh physics samajh nahi aa raha.",
    "bhai canteen aaja, wait kar raha hu.",
    "bhai parking me aaja, wait kar raha hu.",
    "kya aaj shaam ko kuch plan hai?",
    "kya kal raat ko kuch plan hai?",
    "mujhe apne marks dekhe 3 din ho gaye.",
    "mujhe apne marks dekhe 5 din ho gaye.",
    "Rohit ko bol dena ki main late hounga.",
    "Sneha ko bol dena ki main late hounga.",
    "Ankit ko bol dena ki main late hounga.",
    "Devansh ko bol dena ki main late hounga.",
    "Aman ko bol dena ki main late hounga.",
    "Priya ko bol dena ki main late hounga.",
    "Kritika ko bol dena ki main late hounga.",
    "Ishaan ko bol dena ki main late hounga.",
    "aaj 5 baje thoda jaldi free ho jaunga.",
    "aaj 6 baje thoda jaldi free ho jaunga.",
    "kisi ne Rohit ko dekha kya aaj?",
    "kisi ne Sneha ko dekha kya aaj?",
    "kisi ne Ankit ko dekha kya aaj?",
    "kisi ne Devansh ko dekha kya aaj?",
    "kisi ne Aman ko dekha kya aaj?",
    "kisi ne Priya ko dekha kya aaj?",
    "kisi ne Kritika ko dekha kya aaj?",
    "kisi ne Ishaan ko dekha kya aaj?",
    "mujhe auditorium jana hai 2 baje.",
    "mujhe lab jana hai 4 baje.",
    "bhai 4 log aa rahe hain.",
    "bhai 6 log aa rahe hain.",
    "yeh dbms ka assignment kal 5 baje dena hai.",
    "yeh os ka assignment aaj raat ko dena hai.",
    "kisi ne mera phone dekha kya canteen me?",
    "kisi ne mera phone dekha kya lab me?",
    "kal se roz subah 8 baje uthunga.",
    "kal se roz subah 9 baje uthunga.",
    "is baar cn ka paper bahut tough tha.",
    "is baar dsa ka paper bahut tough tha.",
    "aaj dopahar me thodi dhoop hai.",
    "aaj subah thodi dhoop hai.",
    "sir ne kal shaam ko attendance li thi kya?",
    "sir ne aaj dopahar me attendance li thi kya?",
    "bhai mere paas sirf 10 rupe bache hain.",
    "bhai mere paas sirf 20 rupe bache hain.",
    "mujhe lag raha hai cn me back aayegi.",
    "mujhe lag raha hai dsa me back aayegi.",
    "kisi ke paas physics ke notes hain kya?",
    "kisi ke paas chemistry ke notes hain kya?",
    "kya kal os ki class cancel ho gayi?",
    "kya aaj dbms ki class cancel ho gayi?",
    "abhi 1 baj gaye aur neend aa rahi hai.",
    "abhi 3 baj gaye aur neend aa rahi hai.",
    "mujhe apne marks dekhe 2 din ho gaye.",
    "mujhe apne marks dekhe 4 din ho gaye.",
    "aaj parking me koi hai kya?",
    "aaj canteen me koi hai kya?",
    "kisi ko pata hai department kab khulega?",
    "kisi ko pata hai lab kab khulega?",
    "bhai hostel aaja, wait kar raha hu.",
    "bhai library aaja, wait kar raha hu.",
    "kya kisi ne os ki assignment complete ki?",
    "kya kisi ne maths ki assignment complete ki?",
    "mujhe 1 din ki chhutti chahiye.",
    "mujhe 3 din ki chhutti chahiye.",
    "Rohit ko bol dena ki main nahi aa raha.",
    "Sneha ko bol dena ki main nahi aa raha.",
    "Ankit ko bol dena ki main nahi aa raha.",
    "Devansh ko bol dena ki main nahi aa raha.",
    "Aman ko bol dena ki main nahi aa raha.",
    "Priya ko bol dena ki main nahi aa raha.",
    "Kritika ko bol dena ki main nahi aa raha.",
    "Ishaan ko bol dena ki main nahi aa raha.",
    "Rohit kahan hai yaar, message ka reply nahi kar raha.",
    "Sneha kahan hai yaar, message ka reply nahi kar raha.",
    "Ankit kahan hai yaar, message ka reply nahi kar raha.",
    "Devansh kahan hai yaar, message ka reply nahi kar raha.",
    "Aman kahan hai yaar, message ka reply nahi kar raha.",
    "Priya kahan hai yaar, message ka reply nahi kar raha.",
    "Kritika kahan hai yaar, message ka reply nahi kar raha.",
    "Ishaan kahan hai yaar, message ka reply nahi kar raha.",
    "kya Rohit aaj department me tha?",
    "kya Sneha aaj department me tha?",
    "kya Ankit aaj department me tha?",
    "kya Devansh aaj department me tha?",
    "kya Aman aaj department me tha?",
    "kya Priya aaj department me tha?",
    "kya Kritika aaj department me tha?",
    "kya Ishaan aaj department me tha?",
    "kya Rohit kal library me tha?",
    "kya Sneha kal library me tha?",
    "kya Ankit kal library me tha?",
    "kya Devansh kal library me tha?",
    "kya Aman kal library me tha?",
    "kya Priya kal library me tha?",
    "kya Kritika kal library me tha?",
    "kya Ishaan kal library me tha?",
    "mujhe lagta hai Rohit so raha hoga.",
    "mujhe lagta hai Sneha so raha hoga.",
    "mujhe lagta hai Ankit so raha hoga.",
    "mujhe lagta hai Devansh so raha hoga.",
    "mujhe lagta hai Aman so raha hoga.",
    "mujhe lagta hai Priya so raha hoga.",
    "mujhe lagta hai Kritika so raha hoga.",
    "mujhe lagta hai Ishaan so raha hoga.",
    "kal Rohit ka presentation hai na?",
    "kal Sneha ka presentation hai na?",
    "kal Ankit ka presentation hai na?",
    "kal Devansh ka presentation hai na?",
    "kal Aman ka presentation hai na?",
    "kal Priya ka presentation hai na?",
    "kal Kritika ka presentation hai na?",
    "kal Ishaan ka presentation hai na?",
    "aaj Rohit ne class attend ki kya?",
    "aaj Sneha ne class attend ki kya?",
    "aaj Ankit ne class attend ki kya?",
    "aaj Devansh ne class attend ki kya?",
    "aaj Aman ne class attend ki kya?",
    "aaj Priya ne class attend ki kya?",
    "aaj Kritika ne class attend ki kya?",
    "aaj Ishaan ne class attend ki kya?",
    "Rohit ko bolna mujhe call kare.",
    "Sneha ko bolna mujhe call kare.",
    "Ankit ko bolna mujhe call kare.",
    "Devansh ko bolna mujhe call kare.",
    "Aman ko bolna mujhe call kare.",
    "Priya ko bolna mujhe call kare.",
    "Kritika ko bolna mujhe call kare.",
    "Ishaan ko bolna mujhe call kare.",
    "Rohit ka assignment dekha tune?",
    "Sneha ka assignment dekha tune?",
    "Ankit ka assignment dekha tune?",
    "Devansh ka assignment dekha tune?",
    "Aman ka assignment dekha tune?",
    "Priya ka assignment dekha tune?",
    "Kritika ka assignment dekha tune?",
    "Ishaan ka assignment dekha tune?",
    "mujhe lagta hai Rohit ko sab pata hoga.",
    "mujhe lagta hai Sneha ko sab pata hoga.",
    "mujhe lagta hai Ankit ko sab pata hoga.",
    "mujhe lagta hai Devansh ko sab pata hoga.",
    "mujhe lagta hai Aman ko sab pata hoga.",
    "mujhe lagta hai Priya ko sab pata hoga.",
    "mujhe lagta hai Kritika ko sab pata hoga.",
    "mujhe lagta hai Ishaan ko sab pata hoga.",
    "kal Rohit ne mujhe bataya tha iske baare me.",
    "kal Sneha ne mujhe bataya tha iske baare me.",
    "kal Ankit ne mujhe bataya tha iske baare me.",
    "kal Devansh ne mujhe bataya tha iske baare me.",
    "kal Aman ne mujhe bataya tha iske baare me.",
    "kal Priya ne mujhe bataya tha iske baare me.",
    "kal Kritika ne mujhe bataya tha iske baare me.",
    "kal Ishaan ne mujhe bataya tha iske baare me.",
    "Rohit ne bola ki exam postpone ho gaya.",
    "Sneha ne bola ki exam postpone ho gaya.",
    "Ankit ne bola ki exam postpone ho gaya.",
    "Devansh ne bola ki exam postpone ho gaya.",
    "Aman ne bola ki exam postpone ho gaya.",
    "Priya ne bola ki exam postpone ho gaya.",
    "Kritika ne bola ki exam postpone ho gaya.",
    "Ishaan ne bola ki exam postpone ho gaya.",
    "Rohit ki tabiyat kharab hai kya aaj?",
    "Sneha ki tabiyat kharab hai kya aaj?",
    "Ankit ki tabiyat kharab hai kya aaj?",
    "Devansh ki tabiyat kharab hai kya aaj?",
    "Aman ki tabiyat kharab hai kya aaj?",
    "Priya ki tabiyat kharab hai kya aaj?",
    "Kritika ki tabiyat kharab hai kya aaj?",
    "Ishaan ki tabiyat kharab hai kya aaj?",
    "kya Rohit canteen gaya hai?",
    "kya Sneha canteen gaya hai?",
    "kya Ankit canteen gaya hai?",
    "kya Devansh canteen gaya hai?",
    "kya Aman canteen gaya hai?",
    "kya Priya canteen gaya hai?",
    "kya Kritika canteen gaya hai?",
    "kya Ishaan canteen gaya hai?",
    "Rohit ne mujhe aaj subah milne ko bola tha.",
    "Sneha ne mujhe aaj subah milne ko bola tha.",
    "Ankit ne mujhe aaj subah milne ko bola tha.",
    "Devansh ne mujhe aaj subah milne ko bola tha.",
    "Aman ne mujhe aaj subah milne ko bola tha.",
    "Priya ne mujhe aaj subah milne ko bola tha.",
    "Kritika ne mujhe aaj subah milne ko bola tha.",
    "Ishaan ne mujhe aaj subah milne ko bola tha.",
    "mujhe Rohit se baat karni thi yaar.",
    "mujhe Sneha se baat karni thi yaar.",
    "mujhe Ankit se baat karni thi yaar.",
    "mujhe Devansh se baat karni thi yaar.",
    "mujhe Aman se baat karni thi yaar.",
    "mujhe Priya se baat karni thi yaar.",
    "mujhe Kritika se baat karni thi yaar.",
    "mujhe Ishaan se baat karni thi yaar.",
    "aaj Rohit ka phone band aa raha hai.",
    "aaj Sneha ka phone band aa raha hai.",
    "aaj Ankit ka phone band aa raha hai.",
    "aaj Devansh ka phone band aa raha hai.",
    "aaj Aman ka phone band aa raha hai.",
    "aaj Priya ka phone band aa raha hai.",
    "aaj Kritika ka phone band aa raha hai.",
    "aaj Ishaan ka phone band aa raha hai.",
    "Rohit ne kal apna laptop yahan chhod diya tha.",
    "Sneha ne kal apna laptop yahan chhod diya tha.",
    "Ankit ne kal apna laptop yahan chhod diya tha.",
    "Devansh ne kal apna laptop yahan chhod diya tha.",
    "Aman ne kal apna laptop yahan chhod diya tha.",
    "Priya ne kal apna laptop yahan chhod diya tha.",
    "Kritika ne kal apna laptop yahan chhod diya tha.",
    "Ishaan ne kal apna laptop yahan chhod diya tha.",
    "mujhe lagta hai Rohit ko yaad nahi hoga.",
    "mujhe lagta hai Sneha ko yaad nahi hoga.",
    "mujhe lagta hai Ankit ko yaad nahi hoga.",
    "mujhe lagta hai Devansh ko yaad nahi hoga.",
    "mujhe lagta hai Aman ko yaad nahi hoga.",
    "mujhe lagta hai Priya ko yaad nahi hoga.",
    "mujhe lagta hai Kritika ko yaad nahi hoga.",
    "mujhe lagta hai Ishaan ko yaad nahi hoga.",
    "kya Rohit ne attendance mark ki thi?",
    "kya Sneha ne attendance mark ki thi?",
    "kya Ankit ne attendance mark ki thi?",
    "kya Devansh ne attendance mark ki thi?",
    "kya Aman ne attendance mark ki thi?",
    "kya Priya ne attendance mark ki thi?",
    "kya Kritika ne attendance mark ki thi?",
    "kya Ishaan ne attendance mark ki thi?",
    "Rohit se puchh le, usko notes mil gaye the.",
    "Sneha se puchh le, usko notes mil gaye the.",
    "Ankit se puchh le, usko notes mil gaye the.",
    "Devansh se puchh le, usko notes mil gaye the.",
    "Aman se puchh le, usko notes mil gaye the.",
    "Priya se puchh le, usko notes mil gaye the.",
    "Kritika se puchh le, usko notes mil gaye the.",
    "Ishaan se puchh le, usko notes mil gaye the.",
    "kal se barish ho rahi hai yahan.",
    "mess ka khana bilkul acha nahi tha aaj.",
    "kisi ke paas extra pen hai kya?",
    "kya kal chhutti hai college me?",
    "mujhe lagta hai kal practical exam hai.",
    "kisi ne mera id card dekha kya?",
    "aaj ki class bahut lambi thi yaar.",
    "bhai koi placement cell ka update hai kya?",
    "kya Rohit kal ghar ja raha hai?",
    "kya Sneha kal ghar ja raha hai?",
    "kya Ankit kal ghar ja raha hai?",
    "kya Devansh kal ghar ja raha hai?",
    "kya Aman kal ghar ja raha hai?",
    "kya Priya kal ghar ja raha hai?",
    "kya Kritika kal ghar ja raha hai?",
    "kya Ishaan kal ghar ja raha hai?",
    "mujhe lagta hai Rohit party dega aaj.",
    "mujhe lagta hai Sneha party dega aaj.",
    "mujhe lagta hai Ankit party dega aaj.",
    "mujhe lagta hai Devansh party dega aaj.",
    "mujhe lagta hai Aman party dega aaj.",
    "mujhe lagta hai Priya party dega aaj.",
    "mujhe lagta hai Kritika party dega aaj.",
    "mujhe lagta hai Ishaan party dega aaj.",
    "Rohit ko bolna book wapas karde meri.",
    "Sneha ko bolna book wapas karde meri.",
    "Ankit ko bolna book wapas karde meri.",
    "Devansh ko bolna book wapas karde meri.",
    "Aman ko bolna book wapas karde meri.",
    "Priya ko bolna book wapas karde meri.",
    "Kritika ko bolna book wapas karde meri.",
    "Ishaan ko bolna book wapas karde meri.",
    "kya Rohit ne wifi password change kiya?",
    "kya Sneha ne wifi password change kiya?",
    "kya Ankit ne wifi password change kiya?",
    "kya Devansh ne wifi password change kiya?",
    "kya Aman ne wifi password change kiya?",
    "kya Priya ne wifi password change kiya?",
    "kya Kritika ne wifi password change kiya?",
    "kya Ishaan ne wifi password change kiya?",
    "aaj Rohit ka mood kharab lag raha tha.",
    "aaj Sneha ka mood kharab lag raha tha.",
    "aaj Ankit ka mood kharab lag raha tha.",
    "aaj Devansh ka mood kharab lag raha tha.",
    "aaj Aman ka mood kharab lag raha tha.",
    "aaj Priya ka mood kharab lag raha tha.",
    "aaj Kritika ka mood kharab lag raha tha.",
    "aaj Ishaan ka mood kharab lag raha tha.",
    "Rohit ne bola ki trip cancel ho gaya.",
    "Sneha ne bola ki trip cancel ho gaya.",
    "Ankit ne bola ki trip cancel ho gaya.",
    "Devansh ne bola ki trip cancel ho gaya.",
    "Aman ne bola ki trip cancel ho gaya.",
    "Priya ne bola ki trip cancel ho gaya.",
    "Kritika ne bola ki trip cancel ho gaya.",
    "Ishaan ne bola ki trip cancel ho gaya.",
    "kya Rohit ne project submit kar diya?",
    "kya Sneha ne project submit kar diya?",
    "kya Ankit ne project submit kar diya?",
    "kya Devansh ne project submit kar diya?",
    "kya Aman ne project submit kar diya?",
    "kya Priya ne project submit kar diya?",
    "kya Kritika ne project submit kar diya?",
    "kya Ishaan ne project submit kar diya?",
    "mujhe lagta hai Rohit ko internship mil gayi.",
    "mujhe lagta hai Sneha ko internship mil gayi.",
    "mujhe lagta hai Ankit ko internship mil gayi.",
    "mujhe lagta hai Devansh ko internship mil gayi.",
    "mujhe lagta hai Aman ko internship mil gayi.",
    "mujhe lagta hai Priya ko internship mil gayi.",
    "mujhe lagta hai Kritika ko internship mil gayi.",
    "mujhe lagta hai Ishaan ko internship mil gayi.",
    "kal Rohit mere room pe aaya tha.",
    "kal Sneha mere room pe aaya tha.",
    "kal Ankit mere room pe aaya tha.",
    "kal Devansh mere room pe aaya tha.",
    "kal Aman mere room pe aaya tha.",
    "kal Priya mere room pe aaya tha.",
    "kal Kritika mere room pe aaya tha.",
    "kal Ishaan mere room pe aaya tha.",
    "Rohit se kehna mujhe shaam ko mil le.",
    "Sneha se kehna mujhe shaam ko mil le.",
    "Ankit se kehna mujhe shaam ko mil le.",
    "Devansh se kehna mujhe shaam ko mil le.",
    "Aman se kehna mujhe shaam ko mil le.",
    "Priya se kehna mujhe shaam ko mil le.",
    "Kritika se kehna mujhe shaam ko mil le.",
    "Ishaan se kehna mujhe shaam ko mil le.",
    "aaj sports complex kiska plan hai?",
    "kisi ko pata hai fest kab se hai?",
    # --- warmup gold texts (needed by build_corpus warmup queries) ---
    "lab assistant ne mana kar diya sports complex raat ko",
    "aaj lab me bhookh lagi h",
    "yo guys, os class h aaj?",
    "keys mil gaya kya maths?",
    "junior ne bola stairs raat ko",
    "rishikesh sasta h thoda",
    "start karna h kal tak",
    "physics ka practical download karna h",
    "HOD pucha stairs shaam ko",
    "mera charger gym me reh gaya",
    "senior ne bola library 2 baje",
    "file kisi ke pass h network?",
    "placement cell bataya department shaam ko",
    "raat ko milte h sports complex pe",
    "guard postpone kiya auditorium subah",
    "cn ka file complete karna h",
    "physics ka practical start karna h",
    "night guys, chemistry class h aaj?",
    "dean bahut chhota h yaar",
    "lunch kon kon aa rha canteen",
    "senior aayega lab dopahar me",
    "abhi milte h library pe",
    "placement cell bheja h lab friday",
    "aaj milte h lab pe",
    "wo group me sirf dekhta h",
    "maths ka phone print nikalna h",
    "bhaiya ne mana kar diya mess 2 baje",
    "mera phone canteen me reh gaya",
    "ye koi vote nhi h",
    "yeh physics kitna mast h",
    "shaam ko milte h gym pe",
]
